[package]
name = "rusty_mazes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8.5"
image = "^0.24.7"
clap = { version = "4.4.18", features = ["derive"] }
